const Game=(()=>{
const TOTAL=10,KEY="gamepass_v3_remaining";let currentModal=null;
const get=()=>{let v=localStorage.getItem(KEY);if(v===null){localStorage.setItem(KEY,TOTAL);return TOTAL}v=Number(v);return Number.isFinite(v)?Math.max(0,Math.min(TOTAL,v)):TOTAL};
function update(){let n=get();document.getElementById("placesCounter").textContent=n;let h=document.getElementById("ticketLights");h.innerHTML="";for(let i=0;i<TOTAL;i++){let s=document.createElement("i");s.className="ticket-light"+(i<n?"":" off");h.appendChild(s)}}
function outcome(p=.3){if(get()<=0)return{win:false,sold:true};return{win:Math.random()<p,sold:false}}
function win(){let n=get();if(n<=0)return;let no=TOTAL-n+1;localStorage.setItem(KEY,n-1);update();document.getElementById("ticketNumber").textContent=`PLACE #${String(no).padStart(2,"0")}`;document.getElementById("winOverlay").classList.add("open");confetti()}
function confetti(){let h=document.getElementById("confetti");h.innerHTML="";let c=["#4ce6ff","#ffd34e","#ff4f91","#54ee9a","#fff"];for(let i=0;i<65;i++){let e=document.createElement("i");e.className="piece";e.style.left=Math.random()*100+"%";e.style.background=c[i%c.length];e.style.animationDuration=2.3+Math.random()*2+"s";e.style.animationDelay=Math.random()*.6+"s";h.appendChild(e)}}
const templates={
roulette:`<h2>🎡 ROULETTE</h2><p>Lance la roue et laisse le hasard décider.</p><div class="wheel-wrap"><div class="pointer">▼</div><div class="wheel" id="wheel"><div class="wheel-center">GO</div></div></div><button class="primary" id="spin">FAIRE TOURNER</button><div class="result" id="res"></div>`,
scratch:`<h2>🎫 SCRATCH</h2><p>Gratte au moins 45 % du ticket.</p><div class="scratch-card"><div class="scratch-message" id="sm"></div><canvas id="scratchCanvas" width="600" height="260"></canvas></div><button class="secondary" id="newScratch">NOUVEAU TICKET</button><div class="result" id="res"></div>`,
mystery:`<h2>🎁 MYSTERY BOX</h2><p>Trois coffres. Un seul choix.</p><div class="boxes"><button class="box">🎁</button><button class="box">🎁</button><button class="box">🎁</button></div><button class="secondary" id="resetBoxes">REJOUER</button><div class="result" id="res"></div>`,
safe:`<h2>🔐 COFFRE-FORT</h2><p>Les chiffres défilent. Stoppe les trois rouleaux.</p><div class="safe-display"><div class="digit">0</div><div class="digit">0</div><div class="digit">0</div></div><div class="safe-actions"><button class="digit-stop">STOP</button><button class="digit-stop">STOP</button><button class="digit-stop">STOP</button></div><button class="secondary" id="safeRestart">RELANCER</button><div class="result" id="res"></div>`,
stop:`<h2>⚡ STOP ZONE</h2><p>La jauge accélère. Appuie dans la zone verte.</p><div class="meter"><div class="target-zone"></div><div class="meter-fill" id="meterFill"></div><div class="meter-marker" id="marker"></div></div><div class="meter-labels"><span>0</span><span>ZONE CIBLE</span><span>100</span></div><button class="primary" id="stopBtn">DÉMARRER</button><div class="result" id="res"></div>`
};
function open(name){let host=document.getElementById("modalHost");host.innerHTML=`<section class="modal"><div class="backdrop"></div><div class="modal-card"><button class="close">×</button>${templates[name]}</div></section>`;currentModal=name;host.querySelector(".close").onclick=close;host.querySelector(".backdrop").onclick=close;({roulette:initRoulette,scratch:initScratch,mystery:initMystery,safe:initSafe,stop:initStop})[name]()}
function close(){document.getElementById("modalHost").innerHTML="";currentModal=null}
function setRes(text,type=""){let r=document.getElementById("res");if(r){r.textContent=text;r.className="result "+type}}
function initRoulette(){let w=document.getElementById("wheel"),b=document.getElementById("spin"),rot=0;b.onclick=()=>{b.disabled=true;setRes("Rotation en cours...");let o=outcome();rot+=1800+Math.floor(Math.random()*360);w.style.transform=`rotate(${rot}deg)`;setTimeout(()=>{if(o.sold)setRes("Tous les pass ont été remportés.","lose");else if(o.win){setRes("PASS DÉTECTÉ !","win");win()}else setRes("Pas cette fois.","lose");b.disabled=false},4050)}}
function initScratch(){let c=document.getElementById("scratchCanvas"),x=c.getContext("2d"),drawing=false,revealed=false,o;function prep(){revealed=false;o=outcome();document.getElementById("sm").textContent=o.sold?"PLUS DE PASS":o.win?"🎟️ PASS TROUVÉ":"DOMMAGE";c.width=600;c.height=260;x.globalCompositeOperation="source-over";let g=x.createLinearGradient(0,0,600,260);g.addColorStop(0,"#8993a3");g.addColorStop(.5,"#e2e6eb");g.addColorStop(1,"#778292");x.fillStyle=g;x.fillRect(0,0,600,260);x.fillStyle="#374151";x.font="bold 34px system-ui";x.textAlign="center";x.fillText("GRATTE ICI",300,140);x.globalCompositeOperation="destination-out";setRes("")}function point(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*600/r.width,y:(e.clientY-r.top)*260/r.height}}function scratch(e){if(!drawing||revealed)return;let p=point(e);x.beginPath();x.arc(p.x,p.y,38,0,Math.PI*2);x.fill();let d=x.getImageData(0,0,600,260).data,t=0,s=0;for(let i=3;i<d.length;i+=96){s++;if(d[i]===0)t++}if(t/s>.45){revealed=true;x.clearRect(0,0,600,260);if(o.sold)setRes("Tous les pass ont été remportés.","lose");else if(o.win){setRes("Ticket gagnant !","win");setTimeout(win,300)}else setRes("Ticket perdant.","lose")}}c.onpointerdown=e=>{drawing=true;c.setPointerCapture(e.pointerId);scratch(e)};c.onpointermove=scratch;c.onpointerup=()=>drawing=false;document.getElementById("newScratch").onclick=prep;prep()}
function initMystery(){let boxes=[...document.querySelectorAll(".box")],played=false;function reset(){played=false;setRes("");boxes.forEach(b=>{b.disabled=false;b.classList.remove("open");b.textContent="🎁"})}boxes.forEach(b=>b.onclick=()=>{if(played)return;played=true;let o=outcome();boxes.forEach(q=>q.disabled=true);b.classList.add("open");if(o.sold){b.textContent="⛔";setRes("Tous les pass ont été remportés.","lose")}else if(o.win){b.textContent="🎟️";setRes("PASS TROUVÉ !","win");setTimeout(win,300)}else{b.textContent="💨";setRes("Coffre vide.","lose")}});document.getElementById("resetBoxes").onclick=reset}
function initSafe(){let ds=[...document.querySelectorAll(".digit")],bs=[...document.querySelectorAll(".digit-stop")],timers=[],stopped=0,o;function start(){timers.forEach(clearInterval);stopped=0;o=outcome();setRes("Synchronisation des rouleaux...");ds.forEach((d,i)=>{bs[i].disabled=false;timers[i]=setInterval(()=>d.textContent=Math.floor(Math.random()*10),75+i*18)});setTimeout(()=>setRes("STOPPE LES 3 ROULEAUX !"),500)}bs.forEach((b,i)=>b.onclick=()=>{clearInterval(timers[i]);b.disabled=true;stopped++;if(stopped===3){if(o.sold)setRes("Coffre vide : plus aucun pass.","lose");else if(o.win){ds.forEach(d=>d.textContent="7");setRes("777 — COFFRE OUVERT !","win");setTimeout(win,500)}else setRes("CODE REFUSÉ — retente ta chance.","lose")}});document.getElementById("safeRestart").onclick=start;start()}
function initStop(){let b=document.getElementById("stopBtn"),f=document.getElementById("meterFill"),m=document.getElementById("marker"),running=false,val=0,timer=null,o;b.onclick=()=>{if(!running){o=outcome();running=true;val=0;b.textContent="STOP !";setRes("Vise la zone verte...");timer=setInterval(()=>{val+=.9+val*.008;f.style.width=Math.min(val,100)+"%";m.style.left=Math.min(val,100)+"%";if(val>=100)finish()},30)}else finish()};function finish(){if(!running)return;running=false;clearInterval(timer);b.textContent="RECOMMENCER";if(o.sold)setRes("Plus aucun pass disponible.","lose");else if(val>=68&&val<=80&&o.win){setRes(`PARFAIT — ${Math.round(val)}% !`,"win");setTimeout(win,350)}else if(val>=68&&val<=80)setRes(`Zone atteinte (${Math.round(val)}%), mais aucun pass cette fois.`,"lose");else setRes(`Raté : ${Math.round(val)}%. Vise la zone verte.`,"lose")}}
function init(){update();document.querySelectorAll("[data-open-game]").forEach(b=>b.onclick=()=>open(b.dataset.openGame));document.getElementById("resetDemoButton").onclick=e=>{localStorage.setItem(KEY,TOTAL);update();e.target.textContent="✓ RÉINITIALISÉ";setTimeout(()=>e.target.textContent="RESET DÉMO",1200)};document.getElementById("closeWin").onclick=()=>document.getElementById("winOverlay").classList.remove("open");document.addEventListener("keydown",e=>{if(e.key==="Escape")close()})}
return{init}})();document.addEventListener("DOMContentLoaded",Game.init);